In [20]:
import numpy as np

def hadamard_matrix(order):
    """ 生成哈达玛矩阵（Hadamard matrix）"""
    if order < 1 or (order & (order - 1)) != 0:
        raise ValueError("Order must be a power of 2.")

    if order == 1:
        return np.array([[1]])

    h = hadamard_matrix(order // 2)
    return np.block([[h, h], [h, -h]])

def hadamard_transform(matrix):
    """ 对输入矩阵进行哈达玛变换 """
    n, m = matrix.shape
    if n != m or (n & (n - 1)) != 0:
        raise ValueError("Matrix must be square and have dimensions that are powers of 2.")

    h = hadamard_matrix(n)
    return np.dot(h, np.dot(matrix, h)) / n

def inverse_hadamard_transform(matrix):
    """ 对输入矩阵进行逆哈达玛变换。"""
    # 逆哈达玛变换与哈达玛变换相同，因为哈达玛矩阵是其自身的逆矩阵（正交矩阵）。
    return hadamard_transform(matrix)

def threshold(matrix, threshold):
    """ 矩阵中小于阈值的元素设置为0 """
    matrix[abs(matrix) < threshold] = 0
    return matrix

def count_zeros(matrix):
    """ 统计矩阵中0的个数 """
    return np.sum(matrix == 0)

if __name__ == "__main__":
    # np.random.seed(0)  
    # matrix = np.random.randint(0.5, 1.5, (8, 8))
    matrix = np.ones((8, 8))

    print("Input Matrix:")
    print(matrix)
    nnz = count_zeros(matrix)
    print(nnz)

    # 计算哈达玛变换
    matrix = hadamard_transform(matrix)
    print("Hadamard Transform Result:")
    print(matrix)
    nnz = count_zeros(matrix)
    print(nnz)

    # matrix = threshold(matrix, 0.126)
    # print("threshold Transform Result:")
    # print(matrix)
    # nnz = count_zeros(matrix)
    # print(nnz)

    # 计算逆哈达玛变换
    matrix = inverse_hadamard_transform(matrix)
    print("Inverse Hadamard Transform Result:")
    print(matrix)

    matrix = inverse_hadamard_transform(matrix)
    print("Inverse Hadamard Transform Result:")
    print(matrix)

    matrix = hadamard_transform(matrix)
    print("Hadamard Transform Result:")
    print(matrix)


Input Matrix:
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
0
Hadamard Transform Result:
[[8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
63
Inverse Hadamard Transform Result:
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
Inverse Hadamard Transform Result:
[[8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Hadamard Transfo

In [29]:
import numpy as np
from scipy.linalg import hadamard

# 生成一维哈达玛变换函数
def hadamard_transform(data):
    N = data.shape[0]
    H = hadamard(N)
    return np.dot(H, data)

# 对三维数据进行哈达玛变换
def hadamard_transform_3d(data):
    N, M, L = data.shape
    H_N = hadamard(N)
    H_M = hadamard(M)
    H_L = hadamard(L)

    # 按维度逐步变换
    data = np.tensordot(H_N, data, axes=(1, 0))  # 变换第一维
    data = np.tensordot(H_M, data, axes=(1, 1))  # 变换第二维
    data = np.tensordot(H_L, data, axes=(1, 2))  # 变换第三维

    return data

# 对三维数据进行逆哈达玛变换
def ihadamard_transform_3d(data):
    N, M, L = data.shape
    H_N = hadamard(N)
    H_M = hadamard(M)
    H_L = hadamard(L)

    # 按维度逐步变换
    data = np.tensordot(H_N, data, axes=(0, 0))  # 变换第一维
    data = np.tensordot(H_M, data, axes=(0, 1))  # 变换第二维
    data = np.tensordot(H_L, data, axes=(0, 2))  # 变换第三维

    # 归一化
    return data / (N * M * L)


# 示例数据
data_3d = np.random.rand(2, 2, 2)  # 生成随机 2x2x2 的三维数据
print("原始数据:")
print(data_3d)

# 正向变换
transformed_data = hadamard_transform_3d(data_3d)
print("\n哈达玛变换后的数据:")
print(transformed_data)

# 逆向变换
restored_data = ihadamard_transform_3d(transformed_data)
print("\n还原后的数据:")
print(restored_data)

# 验证误差
error = np.max(np.abs(data_3d - restored_data))
print("\n还原误差:")
print(error)


原始数据:
[[[0.12802087 0.58319283]
  [0.00206464 0.19891133]]

 [[0.95612316 0.33044057]
  [0.63839011 0.28085949]]]

哈达玛变换后的数据:
[[[ 3.118003   -1.29362366]
  [ 0.87755186  0.1429236 ]]

 [[ 0.33119454 -1.63523186]
  [ 0.00982671 -0.52647724]]]

还原后的数据:
[[[0.12802087 0.58319283]
  [0.00206464 0.19891133]]

 [[0.95612316 0.33044057]
  [0.63839011 0.28085949]]]

还原误差:
1.1102230246251565e-16
